[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200

fs_permissions = [{ access = "read", path = "./"}]
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config